# Generated by Django 4.2.7 on 2023-11-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(default='https://i.imgur.com/lF1ikCo.jpg'),
        ),
    ]
