# Generated by Django 4.2.7 on 2023-11-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='receta',
            name='image',
            field=models.ImageField(default='images/Receta_defect.png', upload_to=''),
        ),
    ]
