# Generated by Django 4.2.7 on 2023-11-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_receta_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='name',
            field=models.CharField(default='no name', max_length=100),
        ),
    ]
