# Generated by Django 4.2.7 on 2023-11-21 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_receta_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='content',
        ),
        migrations.AddField(
            model_name='receta',
            name='description',
            field=models.TextField(default='Sin descripción.'),
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredients',
            field=models.TextField(default='Sin ingredientes.'),
        ),
        migrations.AddField(
            model_name='receta',
            name='prep_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='receta',
            name='steps',
            field=models.TextField(default='Sin pasos de preparación.'),
        ),
    ]
